import type { CSSProperties } from "react";

export const C = {
  bg: "#0e0f11",
  surface: "#161819",
  surfaceHover: "#1c1e20",
  border: "#2a2d31",
  borderLight: "#363a3f",
  text: "#e2e4e8",
  textMuted: "#8b8f96",
  textDim: "#5c6069",
  accent: "#c8a46e",
  accentDim: "#a3834a",
  accentBg: "rgba(200,164,110,0.08)",
  danger: "#d45454",
  dangerBg: "rgba(212,84,84,0.08)",
  radius: 6,
  radiusLg: 10,
  font: "var(--font-plex-mono), 'IBM Plex Mono', 'SF Mono', 'Fira Code', monospace",
  fontSans: "var(--font-plex-sans), 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
} as const;

export const styles: Record<string, CSSProperties> = {
  // Layout
  root: {
    background: C.bg,
    color: C.text,
    minHeight: "100vh",
    fontFamily: C.fontSans,
    fontSize: 14,
    lineHeight: 1.5,
  },
  main: { maxWidth: 1200, margin: "0 auto", padding: "24px 24px 80px" },

  // Toast
  toast: {
    position: "fixed",
    top: 20,
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 999,
    background: C.surface,
    border: `1px solid ${C.border}`,
    color: C.text,
    padding: "8px 20px",
    borderRadius: C.radius,
    fontFamily: C.font,
    fontSize: 13,
    boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
  },

  // Header
  header: {
    borderBottom: `1px solid ${C.border}`,
    padding: "0 24px",
    background: `linear-gradient(180deg, ${C.surface} 0%, ${C.bg} 100%)`,
  },
  headerInner: {
    maxWidth: 1200,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    height: 56,
    gap: 16,
  },
  backBtn: {
    background: "none",
    border: "none",
    color: C.textMuted,
    cursor: "pointer",
    padding: 4,
    display: "flex",
    alignItems: "center",
    transition: "color 0.15s",
  },
  logoWrap: { display: "flex", alignItems: "center", gap: 10, flex: 1 },
  logoMark: {
    fontFamily: C.font,
    fontWeight: 600,
    fontSize: 13,
    color: C.bg,
    background: C.accent,
    borderRadius: 4,
    padding: "2px 6px",
    letterSpacing: 1,
  },
  logoText: {
    fontFamily: C.font,
    fontWeight: 600,
    fontSize: 16,
    color: C.text,
    letterSpacing: "-0.02em",
  },
  headerActions: { display: "flex", alignItems: "center", gap: 8 },

  // Buttons
  primaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 16px",
    background: C.accent,
    color: C.bg,
    border: "none",
    borderRadius: C.radius,
    fontFamily: C.font,
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
    letterSpacing: "0.01em",
    transition: "all 0.15s",
  },
  ghostBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 16px",
    background: "transparent",
    color: C.textMuted,
    border: `1px solid ${C.border}`,
    borderRadius: C.radius,
    fontFamily: C.font,
    fontWeight: 500,
    fontSize: 13,
    cursor: "pointer",
    transition: "all 0.15s",
  },
  iconBtn: {
    background: "none",
    border: `1px solid ${C.border}`,
    color: C.textMuted,
    borderRadius: C.radius,
    width: 34,
    height: 34,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.15s",
  },
  smallBtn: {
    background: "none",
    border: `1px solid ${C.border}`,
    color: C.textMuted,
    borderRadius: 5,
    width: 32,
    height: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.15s",
  },
  dangerBtn: { borderColor: "transparent" },
  useBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "6px 14px",
    background: C.accentBg,
    color: C.accent,
    border: `1px solid ${C.accent}33`,
    borderRadius: C.radius,
    fontFamily: C.font,
    fontWeight: 600,
    fontSize: 12,
    cursor: "pointer",
    transition: "all 0.15s",
  },

  // Toolbar
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 24,
    flexWrap: "wrap" as const,
  },
  searchWrap: { position: "relative" as const, flex: 1, minWidth: 200 },
  searchIcon: {
    position: "absolute" as const,
    left: 10,
    top: "50%",
    transform: "translateY(-50%)",
    color: C.textDim,
    display: "flex",
  },
  searchInput: {
    width: "100%",
    padding: "8px 12px 8px 34px",
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: C.radius,
    color: C.text,
    fontFamily: C.font,
    fontSize: 13,
  },
  sortWrap: { display: "flex", gap: 4 },
  sortBtn: {
    padding: "6px 12px",
    background: "transparent",
    border: `1px solid ${C.border}`,
    borderRadius: C.radius,
    color: C.textMuted,
    fontFamily: C.font,
    fontSize: 12,
    cursor: "pointer",
    fontWeight: 500,
    transition: "all 0.15s",
  },
  sortBtnActive: {
    background: C.accentBg,
    borderColor: `${C.accent}44`,
    color: C.accent,
  },

  // Cards
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))",
    gap: 14,
  },
  card: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: C.radiusLg,
    padding: 20,
    display: "flex",
    flexDirection: "column" as const,
    gap: 12,
    transition: "border-color 0.2s",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  cardTitle: {
    fontFamily: C.font,
    fontWeight: 600,
    fontSize: 15,
    color: C.text,
    lineHeight: 1.3,
  },
  cardMeta: { display: "flex", gap: 6, flexShrink: 0 },
  varBadge: {
    fontFamily: C.font,
    fontSize: 11,
    fontWeight: 500,
    color: C.accent,
    background: C.accentBg,
    padding: "2px 8px",
    borderRadius: 4,
    whiteSpace: "nowrap" as const,
  },
  useBadge: {
    fontFamily: C.font,
    fontSize: 11,
    fontWeight: 500,
    color: C.textMuted,
    background: `${C.textDim}22`,
    padding: "2px 8px",
    borderRadius: 4,
    whiteSpace: "nowrap" as const,
  },
  cardDesc: { color: C.textMuted, fontSize: 13, lineHeight: 1.5 },
  varList: { display: "flex", flexWrap: "wrap" as const, gap: 5 },
  varTag: {
    fontFamily: C.font,
    fontSize: 11,
    color: C.textDim,
    background: `${C.textDim}15`,
    padding: "2px 7px",
    borderRadius: 3,
  },
  cardActions: {
    display: "flex",
    gap: 6,
    marginTop: "auto",
    paddingTop: 4,
  },

  // Empty state
  empty: { textAlign: "center" as const, padding: "60px 20px" },
  emptyTitle: {
    color: C.textMuted,
    fontFamily: C.font,
    fontSize: 14,
    marginBottom: 16,
  },

  // Editor
  editorTop: { marginBottom: 24 },
  viewTitle: {
    fontFamily: C.font,
    fontWeight: 600,
    fontSize: 20,
    color: C.text,
    letterSpacing: "-0.02em",
  },
  editorLayout: {
    display: "flex",
    gap: 24,
    alignItems: "flex-start",
    flexWrap: "wrap" as const,
  },
  editorMain: { flex: "1 1 500px", minWidth: 0 },
  editorSidebar: {
    flex: "0 0 280px",
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: C.radiusLg,
    padding: 20,
    position: "sticky" as const,
    top: 20,
  },
  label: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    marginBottom: 6,
    fontFamily: C.font,
    fontWeight: 600,
    fontSize: 12,
    color: C.textMuted,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
  },
  optional: {
    fontWeight: 400,
    textTransform: "none" as const,
    letterSpacing: 0,
    fontSize: 11,
    color: C.textDim,
  },
  hint: {
    fontWeight: 400,
    textTransform: "none" as const,
    letterSpacing: 0,
    fontSize: 11,
    color: C.textDim,
    marginLeft: "auto",
  },
  input: {
    width: "100%",
    padding: "9px 12px",
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: C.radius,
    color: C.text,
    fontFamily: C.fontSans,
    fontSize: 14,
  },
  textarea: {
    width: "100%",
    padding: "10px 12px",
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: C.radius,
    color: C.text,
    fontFamily: C.font,
    fontSize: 13,
    lineHeight: 1.6,
    resize: "vertical" as const,
    minHeight: 200,
  },
  editorActions: {
    display: "flex",
    gap: 10,
    justifyContent: "flex-end",
    marginTop: 24,
    paddingTop: 20,
    borderTop: `1px solid ${C.border}`,
  },

  // Sidebar
  sidebarTitle: {
    fontFamily: C.font,
    fontWeight: 600,
    fontSize: 12,
    color: C.textMuted,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    marginBottom: 14,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  varCount: {
    fontFamily: C.font,
    fontSize: 11,
    fontWeight: 600,
    color: C.accent,
    background: C.accentBg,
    padding: "1px 7px",
    borderRadius: 10,
  },
  sidebarEmpty: {
    color: C.textDim,
    fontSize: 12,
    fontFamily: C.font,
    lineHeight: 1.6,
  },
  varEditor: { display: "flex", flexDirection: "column" as const, gap: 14 },
  varEditorItem: { display: "flex", flexDirection: "column" as const, gap: 5 },
  varCode: {
    fontFamily: C.font,
    fontSize: 12,
    color: C.accent,
    fontWeight: 500,
  },
  varInput: {
    width: "100%",
    padding: "6px 9px",
    background: C.bg,
    border: `1px solid ${C.border}`,
    borderRadius: 4,
    color: C.text,
    fontFamily: C.fontSans,
    fontSize: 12,
  },

  // Use view
  useHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    marginBottom: 24,
  },
  useDesc: { color: C.textMuted, fontSize: 13, marginTop: 4 },
  useLayout: {
    display: "flex",
    gap: 24,
    alignItems: "flex-start",
    flexWrap: "wrap" as const,
  },
  useForm: {
    flex: "0 0 340px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 16,
  },
  formTitle: {
    fontFamily: C.font,
    fontWeight: 600,
    fontSize: 12,
    color: C.textMuted,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
  },
  formField: { display: "flex", flexDirection: "column" as const, gap: 5 },
  formLabel: { display: "flex", flexDirection: "column" as const, gap: 2 },
  formVarName: {
    fontFamily: C.font,
    fontSize: 13,
    fontWeight: 600,
    color: C.accent,
  },
  formHint: { fontSize: 11, color: C.textDim },
  formInput: {
    width: "100%",
    padding: "8px 10px",
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: C.radius,
    color: C.text,
    fontFamily: C.fontSans,
    fontSize: 13,
  },
  formTextarea: {
    width: "100%",
    padding: "8px 10px",
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: C.radius,
    color: C.text,
    fontFamily: C.fontSans,
    fontSize: 13,
    resize: "vertical" as const,
    lineHeight: 1.5,
  },
  formActions: { display: "flex", gap: 8 },

  // Preview
  usePreview: { flex: 1, minWidth: 0 },
  previewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  copyBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 16px",
    background: C.accent,
    color: C.bg,
    border: "none",
    borderRadius: C.radius,
    fontFamily: C.font,
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
    transition: "all 0.15s",
  },
  copyBtnDone: { background: "#3a9a5c" },
  previewBody: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: C.radiusLg,
    padding: 20,
    fontFamily: C.font,
    fontSize: 13,
    lineHeight: 1.7,
    color: C.text,
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
    maxHeight: "70vh",
    overflowY: "auto" as const,
  },
  previewNote: {
    color: C.textDim,
    fontSize: 11,
    fontFamily: C.font,
    marginTop: 8,
  },
};
